name: 'Conan Create'
description: 'Builds conan package from recipe'

inputs:
  runner:
    description: Name of Github Actions runner to use
    required: true
    type: string
  package_name:
    description: Name of conan package to build
    required: true
    type: string
  recipe_dir:
    description: Path to recipe
    default: '.'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - id: conan
      uses: turtlebrowser/get-conan@v1.1
    - run: conan create ${{ inputs.recipe_dir }} ${{ inputs.package_name }}
      shell: bash
