name: 'Conan Create'
description: 'Builds conan package from recipe'

inputs:
  package_id:
    description: Id of conan package to build
    required: true
    type: string
  recipe_dir:
    description: Path to recipe
    default: '.'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - id: conan
      uses: turtlebrowser/get-conan@v1.1
    - run: conan create ${{ inputs.recipe_dir }} ${{ inputs.package_id }}
      shell: bash
